### ISSUE TITLE
lapFinishTimes Array Theory

### ISSUE THREAD

**Issue by kierio04** [SeekyCt/mkw-structures#12]
> Timer * Lap Finish Times; // array of 12 for... some reason

I believe this is due to there being 4 players and then 3 lap finish times for each of the 4 players. (may be wrong but worth testing)

**Comment by CLF78** [comment]
It's not an array of 12 at all, the size of the buffer used in the constructor is `lapCount * sizeof(Timer) + 0x10.` Also different local players wouldn't need their times merged.

**Comment by SeekyCt** [comment]
Yeah, each local player has their own RaceInfoPlayer so they wouldn't all be in one of these arrays. Looked over it in Ghidra and you're right CLF, I guess I just saw the 0xc in the call to __construct_new_array and thought it was the count lol, will correct it now
